### PR TITLE
Model

### PR DESCRIPTION
**Pull request by humanpose1**
@CCInc 
I'm adding the API and some models. `BaseModel `is missing so it does not work yet. I'll add a minimum version soon

### CODE REVIEW

**Comment by humanpose1** [comment]
Actually, I'm not sure that we need a `BaseModel`. Because we have `PointCloudBaseModel` which is a pytorch lightning module. So we can clearly separate the backbone (models from API, etc) and the lightning Module (manage the optimizer and the scheduler, etc)

**Comment by clee-ai** [comment]
Yeah, my thought was the `APIModel` would subclass `PointCloudBaseModel` and we would keep the backbone model separate.

**Comment by clee-ai** [comment]
Also I was thinking we could clean up the integration between ModelFactory and the backbones as well. One way we could do that is taking advantage of Hydra to instantiate the model config rather than doing it within python. For example, for the sparseconv net, we could have something like:

```
  down_conv:
    _target_: torch_points3d.modules.sparseconv3d.modules.ResNetDown
    block: torch_points3d.modules.sparseconv3d.modules.ResBlock
    N: [ 0, 1, 2, 2, 3 ]
    down_conv_nn:
      [
        [ FEAT, in_feat ],
        [ in_feat, in_feat ],
        [ in_feat, 2*in_feat ],
        [ 2*in_feat, 4*in_feat ],
        [ 4*in_feat, 8*in_feat ],
      ]
    kernel_size: 3
    stride: [ 1, 2, 2, 2, 2 ]
```

**Comment by humanpose1** [comment]
Sure we can integrate it in an other PR.

**Comment by humanpose1** [comment]
I've added a very basic test of APIModel. I add more simple tests and then, if it's ok I think we can merge this branch

**Comment by humanpose1** [comment]
Ok I'll merge this code

**Pull request merged**
